"""Helpers for generating `studio_requests.hex` payload files.

`studio_requests.hex` is the case-data file the shared `ble-studio-host` app
(this repo's top-level `ble-studio-host/`) embeds at build time: one
hex-encoded, framed (SOF/ESC/EOF) `zmk.studio.Request` per line, `#` comments
allowed. A module's checked-in `generate_requests.py` builds the Request
protos (against the workspace's real `zmk-studio-messages` protos -- never
hand-encoded bytes), and this module does the rest: framing, rendering,
writing, and an optional `--check` mode for CI.

A module-side generator reduces to ~20 lines:

    from studio_requests import generator_main

    def build_requests(studio_pb2):
        req = studio_pb2.Request()
        req.request_id = 1
        req.custom.list_custom_subsystems.SetInParent()
        return [("list_custom_subsystems", req)]

    if __name__ == "__main__":
        generator_main(build_requests, __file__)

(plus the small sys.path bootstrap that locates this file -- see
`tests/ble/studio/core/generate_requests.py` for a complete sample.)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# The Renode harness (proto compilation + Studio framing) is a sibling lib.
_RENODE_LIB = Path(__file__).resolve().parent.parent / "renode"
sys.path.insert(0, str(_RENODE_LIB))
from renode_harness import (  # noqa: E402
    compile_protos,  # noqa: F401  (re-exported for module protos)
    find_studio_proto_dir,
    frame,
    load_studio_pb2,
)

__all__ = [
    "compile_protos",
    "frame",
    "load_workspace_studio_pb2",
    "render_hex",
    "generator_main",
]


def load_workspace_studio_pb2():
    """Compile + import zmk-studio-messages' studio_pb2 from the enclosing
    west workspace (resolved via the west manifest, with a recursive-search
    fallback)."""
    from west.util import west_topdir

    topdir = Path(west_topdir())
    try:
        from west.manifest import Manifest

        for project in Manifest.from_topdir().projects:
            if project.name == "zmk-studio-messages":
                candidate = Path(project.abspath) / "proto" / "zmk"
                if candidate.is_dir():
                    return load_studio_pb2(candidate)
    except Exception:
        pass
    return load_studio_pb2(find_studio_proto_dir(topdir))


def _normalize(requests) -> list[tuple[str, object]]:
    """Accept a list of Request messages or (name, Request) tuples."""
    named = []
    for i, entry in enumerate(requests):
        if isinstance(entry, tuple):
            named.append(entry)
        else:
            named.append((f"request_{i}", entry))
    return named


def render_hex(requests) -> str:
    """Render framed requests as a `studio_requests.hex` file body."""
    lines = [
        "# GENERATED by generate_requests.py -- DO NOT EDIT.",
        "# Edit the generator and re-run it to change the request sequence.",
        "#",
        "# One hex-encoded, framed (SOF/ESC/EOF) zmk.studio.Request per line;",
        "# the ble-studio-host app sends them in order, one per response.",
    ]
    for name, req in _normalize(requests):
        lines.append(f"# {name}")
        lines.append(frame(req.SerializeToString()).hex().upper())
    return "\n".join(lines) + "\n"


def parse_hex_file(path: Path) -> list[bytes]:
    """Parse a studio_requests.hex file into framed payload byte strings
    (used by ble-studio-host's hex2inc.py and available for tests)."""
    payloads = []
    for raw in Path(path).read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        payloads.append(bytes.fromhex(line))
    return payloads


def generator_main(build_requests, generator_file, default_output=None) -> int:
    """CLI entry point for a module's generate_requests.py.

    `build_requests(studio_pb2)` returns the request sequence (Request
    messages or (name, Request) tuples). `generator_file` is the module
    generator's `__file__`; the default output is `studio_requests.hex` next
    to it (override with `default_output` or `-o`).
    """
    if default_output is None:
        default_output = Path(generator_file).resolve().parent / "studio_requests.hex"

    ap = argparse.ArgumentParser(
        description="Generate the studio_requests.hex payload file for ble-studio-host."
    )
    ap.add_argument(
        "-o",
        "--output",
        default=str(default_output),
        help=f"output path (default: {default_output})",
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the output file is not byte-identical to what would be generated",
    )
    args = ap.parse_args()

    content = render_hex(build_requests(load_workspace_studio_pb2()))

    out = Path(args.output)
    if args.check:
        current = out.read_text() if out.is_file() else ""
        if current != content:
            print(f"{out} is out of date; re-run the generator", file=sys.stderr)
            return 1
        print(f"{out} is up to date")
        return 0

    out.write_text(content)
    print(f"wrote {out} ({len(content)} bytes)")
    return 0
